### ISSUE TITLE
build  error

### ISSUE THREAD

**Issue by tncyysl** [sametsazak/mergen#3]
when i try build via xcode. i getting below error code ?

/Users/xxx/Documents/mergen/mergen.xcodeproj One of the paths in DEVELOPMENT_ASSET_PATHS does not exist: /Users/xxx/Documents/mergen/mergen/Preview

is this normal ?

**Comment by jansuz** [comment]
Ensure that the 'Preview' directory and the 'Preview Contents' directories exist. If they don't, create them.

**Comment by twoziant** [comment]
@jansuz, worked for me. @sametsazak could you just add this hint inside the Readme.md? From my perspective a lot of people using this application do not handle X-Code projects normally. And props for the tool - helped me a lot 👍

**Comment by sametsazak** [comment]
@jansuz thank you. I forgot to add 'Preview' and the 'Preview Contents' directories. Fixing soon.

**Comment by sametsazak** [comment]
Done.
