### ISSUE TITLE
On mac using Dark mode, text on start page is unreadable

### ISSUE THREAD

**Issue by detlefs** [sametsazak/mergen#8]
If user enabled dark mode in settings and starts Mergen, the text of the buttons next to "Please choose a scan category" are virtually unreadable. See screenshot:
![Bildschirmfoto 2023-04-29 um 13 12 29](https://user-images.githubusercontent.com/303976/235299657-c3b4ebb1-3fe5-47ba-9d56-b1a79f186561.png)

The scan results are readable, but the colors are not optimized:
![Bildschirmfoto 2023-04-29 um 13 14 00](https://user-images.githubusercontent.com/303976/235299718-2bf85b92-bb16-4d32-8453-b0561b7a2dee.png)

As dark mode is a native feature of MacOS it should natively be supported my Mergen.

**Comment by sametsazak** [comment]
Easy to fix. I will fix it with a minor update. Thank you. @detlefs

**Comment by sametsazak** [comment]
Fixed with a minor update.

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/10809726/236245832-35784a2d-befb-407a-ac8c-9be730d33d83.png">
